Repository awslabs/aws-cloudsaga, pull requests merged in 2022-02, with the labels that each got.

#3 Adjust project structure and introduce pyproject.toml
  .gitignore
  cloudsaga/__init__.py
  cloudsaga/cloudsaga.py
  cloudsaga/scenarios/__init__.py
  cloudsaga/scenarios/iam_credentials.py
  cloudsaga/scenarios/imds_reveal.py
  cloudsaga/scenarios/mining_bitcoin.py
  cloudsaga/scenarios/network_changes.py
  cloudsaga/scenarios/public_resources.py
  poetry.lock
  pyproject.toml
Labels: enhancement

#4 1.0.1
  .gitignore
  CHANGELOG.md
  README.md
  cloudsaga/__init__.py
  cloudsaga/cloudsaga.py
  cloudsaga/scenarios/__init__.py
  cloudsaga/scenarios/iam_credentials.py
  cloudsaga/scenarios/imds_reveal.py
  cloudsaga/scenarios/mining_bitcoin.py
  cloudsaga/scenarios/network_changes.py
  cloudsaga/scenarios/public_resources.py
  poetry.lock
  pyproject.toml
Labels: documentation, enhancement

#5 Enable automatic release to PyPi on tag
  .github/workflows/publish.yml
Labels: documentation, enhancement

#6 Update the readme to reflect new entrypoint usage
  README.md
Labels: documentation
